### PR TITLE
publish as a public npm repository

### PR DESCRIPTION
**Pull request by mohit**
publish this repo as a public npm repository called `clever-discovery`. This would require chaning the package.json in repos depending on discovery.

### CODE REVIEW

**Comment by nathanleiby** [comment]
👍

**Comment by mohit** [comment]
Deploy plan for this:

* merge to master and publish the current version as `clever-discovery` on npm. 
* Make PRs on repos that utilize the private package for them to use the public package. 
* PROFIT!!

**Comment by mohit** [comment]
Details about moving repositories in `INFRA-1581`

**Comment by burnsed** [comment]
LGTM

**Pull request merged**
